server:
  port: 8080

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0

spring:
  application:
    name: MyApp

  datasource:
    url: jdbc:postgresql://localhost:54321/mydatabase
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  messages:
#    always-use-message-format: true
#    basename: i18/message, validation
#    encoding: UTF-8
#    use-code-as-default-message: true
#    cache-duration: 1h

logging:
  level:
    org.springframework: DEBUG
